BoltzExchange/boltz-frontend

- .travis.yml
- package-lock.json
- package.json
- src/components/button/index.js
This PR fixed the Travis build and a linting error
> fix: minor linting error

- src/components/prompt/index.js
- src/views/refund/refund.js
- src/views/swap/swap.js
Adds a component which will alert the user if he refreshes or attempts to close the browser tab while in the middle of a refund/swap.
> feat: Prompt component

- src/components/swaptab/index.js
> refactor: change default send amount

- src/views/swap/steps.js
> refactor: swap invoice placeholder

- src/components/input/index.js
- src/components/swaptab/index.js
> refactor: visual indicator if swap can be initiated

- src/components/controls/index.js
- src/views/refund/refund.js
- src/views/refund/refundActions.js
- src/views/refund/steps.js
> feat: indicate upload

- src/views/landingpage/landingpageActions.js
- src/views/swap/swapActions.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/27 to be merged first
> refactor: change OrderSide to strings

- src/scripts/utils.js
- src/views/swap/steps.js
> refactor: remove satoshi

- src/components/input/index.js
- src/components/swaptab/index.js
- src/views/swap/swapActions.js
> feat: make "You receive" input editable

- src/components/stepswizard/index.js
> refactor: change exit button in complete page

- src/components/controls/index.js
- src/components/loader/index.js
- src/components/swaptab/index.js
- src/views/swap/index.js
- src/views/swap/steps/inputInvoice.js
- src/views/swap/swap.js
- src/views/swap/swapActions.js
- src/views/swap/swapReducer.js
> Loading homepage

- package-lock.json
- src/views/refund/refund.js
- src/views/refund/refundActions.js
- src/views/refund/refundReducer.js
- src/views/refund/steps/completeRefund.js
- src/views/swap/swapActions.js
This PR:
- takes care of handling the events of the normal Swap flow properly
- fixes refunds by ordering the arguments of `constructRefundTransaction` correctly
> Minor fixes

- src/views/refund/index.js
- src/views/refund/refund.js
- src/views/refund/steps/completeRefund.js
- src/views/refund/steps/uploadRefundFile.js
> refactor: update refund flow

- package-lock.json
- package.json
- src/components/modal/index.js
- src/views/landingpage/landingpage.js
> feat: add modal

- package-lock.json
- package.json
- src/components/inputarea/index.js
- src/components/swaptab/index.js
- src/views/landingpage/landingpage.js
- src/views/reverse/index.js
- src/views/reverse/reverse.js
- src/views/reverse/reverseActions.js
- src/views/reverse/reverseReducer.js
- src/views/reverse/steps/payInvoice.js
- src/views/swap/index.js
- src/views/swap/steps/inputInvoice.js
- src/views/swap/swap.js
- src/views/swap/swapActions.js
- src/views/swap/swapReducer.js
> feat: Lightning Joule integration

- package-lock.json
- src/components/swaptab/index.js
- src/constants/actions/index.js
- src/scripts/utils.js
- src/views/landingpage/index.js
- src/views/landingpage/landingpage.js
- src/views/landingpage/landingpageActions.js
- src/views/landingpage/landingpageReducer.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/45
> feat: get limits from middleware api

- src/views/reverse/reverseActions.js
- src/views/swap/steps/inputInvoice.js
The `makeInvoice` function takes satoshis and not whole coins as argument and in a recent PR I broke it and this will fix it again.
> fix: Joule make invoice amounts

- src/components/controls/index.js
- src/components/loading/index.js
- src/views/reverse/index.js
- src/views/reverse/reverse.js
- src/views/reverse/reverseReducer.js
- src/views/reverse/steps/index.js
- src/views/reverse/steps/inputAddress.js
- src/views/reverse/steps/lockingFunds.js
> refactor: update-reverse

- src/components/background/index.js
> refactor: alignment issues

- src/action/navigation/index.js
- src/constants/routes/index.js
- src/views/refund/refund.js
- src/views/reverse/index.js
- src/views/reverse/reverse.js
- src/views/reverse/reverseActions.js
- src/views/reverse/steps/lockingFunds.js
- src/views/reversetimelock/dataStorage.js
- src/views/reversetimelock/index.js
- src/views/reversetimelock/reverseSwapTimelockExpired.js
- src/views/router/Router.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/55
This PR should show the user this page when the time lock of reverse swaps expires and Boltz refunds the locked up funds:
> Timelock expired

- src/views/reverse/reverse.js
- src/views/reverse/steps/inputAddress.js
> feat: verify address provided by user is valid

- src/views/swap/swapActions.js
> feat: add reconnecting logic to normal swaps

- src/views/landingpage/landingpage.js
According to the feedback of @armurbalda on the announcement I also changed the `Low Fee` to `Account Free` on the landing page of Boltz.
> refactor: change low fee to account free

- src/scripts/utils.js
- src/views/landingpage/landingpage.js
Since @peartobear encountered some problems when trying to use Boltz on his iPhone we figured that it would be sensible to show a warning on mobile devices
> feat: warning for mobile users

- src/components/swaptab/index.js
> chore: updated the errorMessage

- src/views/refund/refundActions.js
> feat: show block explorer link for non final transactions

- src/components/swaptab/index.js
This PR enables the swaps to onchain BTC again
> fix: enable Bitcoin onchain swaps again

- src/views/refund/refundActions.js
In https://github.com/BoltzExchange/boltz-frontend/pull/166 I added the feature that allows the user to open a link to a block explorer when clicking "OK" on the error dialog of non final refund transactions. But that link points to the refund transaction (that does not exist at that point in time) instead of the lockup transaction.
This PR fixed the link
> fix: block explorer link in non final dialog

- .github/ISSUE_TEMPLATE/bug_report.md
- src/components/swaptab/index.js
I think the problem was that I edited the issue template locally and it needs to be added throw the issue template editor
> Update issue templates

- src/__test__/unit/reducers/SwapReducer.spec.js
- src/reducers/swapReducer.js
- src/views/swap/index.js
- src/views/swap/swap.js
closes #179 
Lets user executes another swap only if the response has failed.
> feat: wait for response to send another request

- package-lock.json
- package.json
- src/actions/swapActions.js
- src/constants/index.js
Handles the new event introduced in https://github.com/BoltzExchange/boltz-middleware/pull/94
> feat: handle aborted swaps

- package-lock.json
- package.json
- src/__test__/unit/reducers/SwapReducer.spec.js
- src/actions/reverseActions.js
- src/components/swaptab/desktopswaptab.js
- src/components/swaptab/mobileswaptab.js
- src/components/swaptab/swaptabwrapper.js
- src/reducers/swapReducer.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/96
> fix: fee calculation

- package-lock.json
- package.json
- src/views/reverse/reverse.js
- src/views/reverse/steps/lockingFunds.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/98
This PR allows the users to accept 0-conf reverse swaps outputs via a switch
> feat: handle zero conf swaps

- src/utils/index.js
> fix: remove whitespace when copying addresses and invoices

- src/components/swaptab/desktopswaptab.js
- src/components/swaptab/mobileswaptab.js
- src/components/swaptab/swaptabwrapper.js
- src/components/text/index.js
> feat: add fee percentage

- package-lock.json
- package.json
- src/__test__/unit/action/RefundActions.spec.js
- src/actions/refundActions.js
- src/components/dropzone/index.js
- src/components/fileupload/index.js
- src/utils/index.js
- src/utils/refundUtils.js
- src/views/refund/steps/uploadRefundFile.js
- src/views/swap/steps/downloadRefund.js
In preparation for https://github.com/BoltzExchange/boltz-backend/issues/160
> feat: switch from refund JSON to QR code

- package-lock.json
- package.json
- src/views/swap/steps/downloadRefund.js
Closes [#160](https://github.com/BoltzExchange/boltz-backend/issues/160)
Closes [#145](https://github.com/BoltzExchange/boltz-backend/issues/145) 
Please squash and merge after linting fixes @michael1011
> feat: iOS compatible refund flow

- src/components/modalcontent/index.js
- src/views/swap/steps/downloadRefund.js
> chore: fix typos

- src/components/inputarea/index.js
- src/components/qrcode/index.js
- src/views/reverse/steps/payInvoice.js
This PR fixes some minor bugs introduced by #229
> Fix hold reverse swaps
