BoltzExchange/boltz-frontend

src/components/swaptab/index.js, src/scripts/utils.js, src/views/landingpage/landingpageActions.js, src/views/swap/swapActions.js
This PR:
- updates the message when it is waiting for the invoice to be paid so that it ends with `...`
- fixes an error that caused a different amounts to be shown on the landing and first page of the swap
=> Minor fixes

src/components/swaptab/index.js, src/views/landingpage/landingpage.js
Closes #34 
I think we should discuss the UI design of this one
=> feat: add loading state to swaptab

.env, .gitignore, src/constants/index.js
Closes #17 
This makes the API endpoint and networks for Bitcoin and Litecoin configurable with environment variables.
The command `npm run build` that compiles the optimized builds for production [prioritizes the file `.env.production` over the default `.env` file](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#what-other-env-files-can-be-used). This way one can configure the production build so that is uses the correct values without making any changes to the files that are in the repository.
=> feat: use environment variables for API and networks

src/components/swaptab/index.js
=> feat: more versatile errors on homepage

src/views/refund/refundActions.js, src/views/reverse/reverse.js, src/views/reverse/reverseActions.js, src/views/swap/swapActions.js
This PR should cause the errors that pop up when a swap fails to show the actual error message that is returned by the middleware.
=> fix: show errors of failed requests

.eslintrc, src/components/swaptab/index.js
To store the selected assets and entered amount of the user I went with [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). When opening the site the user should either see the default values if it is the first time the site is opened or the assets selected the last time Boltz was used.
=> feat: store assets and base amount in local storage

src/components/background/index.js, src/components/swaptab/index.js
When selecting two invalid assets, close the window and open Boltz again it should show you the error message again.
=> fix: validate assets after mounting component

src/components/swaptab/index.js, src/components/text/index.js, src/views/swap/swap.js
Depends on: https://github.com/BoltzExchange/boltz-middleware/pull/56
=> feat: calculate trading fee

src/components/controls/index.js, src/constants/index.js, src/views/reverse/reverseActions.js, src/views/swap/swap.js, src/views/swap/swapActions.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/61
=> feat: show error if invoice could not be paid

src/components/swaptab/index.js
Inputting a base quote amount ("You receive") throws an error or simply doesn't work if the JavaScript is compiled with `npm run build`. This PR fixed that bug.
=> fix: calculation of base amount

src/views/landingpage/landingpage.js
This PR causes the `Could not enable WebLN` error just to be printed in the console instead of shown to the user because it gets really annoying when one sees it after every reload in a browser that doesn't support webln.
=> fix: show webln warning just in console

src/components/swaptab/index.js
Closes https://github.com/BoltzExchange/boltz-frontend/issues/144
Once this PR and https://github.com/BoltzExchange/boltz-backend/pull/101 are merged the fee estimation of the `LTC/BTC` should finally be correct
=> fix: fee calculation of quote amount

src/components/swaptab/index.js
This PR disables the user from inputting values when attempting to send unsupported pairs.
=> feat: disable inputs when rate is undefined

package-lock.json, src/components/swaptab/index.js, src/constants/index.js, src/views/landingpage/index.js, src/views/landingpage/landingpage.js, src/views/landingpage/landingpageActions.js, src/views/landingpage/landingpageReducer.js
Depends on https://github.com/BoltzExchange/boltz-middleware/pull/80
The frontend will show `Currently unavailable` if the base asset is Lightning and the reverse swaps are disabled
=> feat: show error if reverse swaps are disabled

src/components/swaptab/index.js
closes #150 
The issue @MikeD123 was talking about where he inputs incorrect data then refreshes and the data persist was due to caching of user input every time, this behavior seems unnecessary to me.
@michael1011 @peartobear Should we add a notification or something to recommend the users install joule? Personally, I don't think we should push a certain product and just make a nice list in the FAQ section. Or write a nice blog post about the options out there @michael1011 ;)
=> refactor: dont cache user input

src/views/swap/steps/inputInvoice.js, src/views/swap/swapActions.js
Closes https://github.com/BoltzExchange/boltz-backend/issues/102
The `lightning:` prefix will be valid in the input field for the invoice and removed before making the request to the middleware.
=> fix: trim "lightning:" prefix of invoices

src/__test__/unit/action/DataStorage.spec.js, src/actions/datastorageActions.js, src/actions/navigation.js, src/actions/reverseActions.js, src/actions/swapActions.js, src/constants/index.js, src/constants/routes/index.js, src/views/index.js, src/views/landingpage/index.js, src/views/reverse/index.js, src/views/reverse/reverse.js, src/views/reversetimelock/ReverseSwapTimelockExpired.js
Fixes issues caused by https://github.com/BoltzExchange/boltz-backend/pull/120 and https://github.com/BoltzExchange/boltz-middleware/pull/92
- the preimage from the backend is [`hex` instead of `base64` encoded](https://github.com/BoltzExchange/boltz-backend/pull/120/files#diff-7c6cb229dda4862e288b2a4ed3d63cccR340) from now on
- the new `TransactionClaimed` event is treated exactly like the already existing `InvoicePaid` one because the solely difference is whether Boltz claimed the onchain coins
=> fix: set encoding of preimages to hex

src/components/prompt/index.js, src/views/reverse/reverse.js, src/views/swap/swap.js
When doing  two reverse swaps consecutively without reloading the page claiming the swap output failed. This fixes that bug by forcing the page to reload when clicking on *"Swap again"*
=> fix: claim transaction when doing two reverse swaps

src/actions/reverseActions.js, src/views/reverse/reverse.js
Closes https://github.com/BoltzExchange/boltz-backend/issues/155
=> fix: bug that caused success page after confirmation of 0-conf

src/components/inputarea/index.js
Because some QR codes have a prefix like "bitcoin:" or "litecoin:" this commit causes all prefixes to be removed after a QR code is scanned.
=> fix: trim prefix of scanned QR code data
